stages:
  - uibuild
  - build
  - docker
  - deploy

.ui build:
  stage: uibuild
  image: node:latest
  script:
    - cd poker-ui-app && yarn install && mkdir -p node_modules/.cache/kotlin-webpack && yarn build && echo "missing kotlinc ..."
  artifacts:
    paths:
      - poker-ui-app/build/*

gradle build:
  stage: build
  image: gradle:5.5
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"
    KOTLIN_VERSION: "1.3.50"
  script:
    - |
      wget -k "https://github.com/JetBrains/kotlin/releases/download/v$KOTLIN_VERSION/kotlin-compiler-$KOTLIN_VERSION.zip" && \
      unzip "kotlin-compiler-$KOTLIN_VERSION.zip" && \
      chmod +x kotlinc/bin/* && export PATH=$PATH:`pwd`/kotlinc/bin && echo $PATH
    - unset CI
    - cd poker-ui-app && gradle npm_install_-g_create-react-kotlin-app && gradle npm_run_build && cd ..
    - cat /home/gradle/.npm/_logs/*.log || true
    - mv poker-ui-app/build main/src/main/resources/public
    - gradle --build-cache --scan assemble check coverage detekt
    - 'cat ''build/reports/jacoco/coverage/html/index.html'' | sed -n ''s/.*Total[^%]*>\([0-9]*%\).*/Coverage: \1/pg'''
  coverage: /Coverage[^0-9]*([0-9]{1,3})%/
  artifacts:
    paths:
      - main/build/libs/*.jar
  cache:
    key: "gonzalez"
    paths:
      - build
      - .gradle

docker build:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    - master
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE

deploy:
  stage: deploy
  image: registry.gitlab.rotate-it.be/tripled/containers/devops
  only:
    - master
  environment: 
    name: production
    url: https://poker.otd.rotate-it.be
  script:
    - kubectl get nodes
    - kubectl get sa default
    - create_secret
    - sed -i "s|commithash|$CI_COMMIT_SHA|" main/src/main/resources/k8s/poker.yaml
    - kubectl --namespace="$KUBE_NAMESPACE" apply -f main/src/main/resources/k8s/poker.yaml
