build:
  image: gradle:latest
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: build
  script: GRADLE_USER_HOME=`pwd`/.gradle ./gradlew --build-cache assemble jacocoTestReport
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle