build:
  image: gradle:latest
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"
  stage: build
  script: 
    - gradle --build-cache --scan assemble check jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html | grep Total # coverage
  coverage: /Total.*?([0-9]{1,3})%/
  cache:
    key: "gonzalez"
    paths:
      - build
      - .gradle