apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: poker
  namespace: poker-265
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: registry.gitlab.rotate-it.be/tripled/poker:latest
            env:
              - name: TARGET
                value: "Spring Boot Sample v1"
