apiVersion: apps/v1
kind: Deployment
metadata:
  name: poker
  annotations:
    app.gitlab.com/app: "tripled-poker"
    app.gitlab.com/env: "production"
  labels:
    app: production
    release: production
    track: stable
spec:
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      labels:
        app: production
        release: production
        track: stable
        commit: commithash
      annotations:
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: poker-server
          image: "registry.gitlab.rotate-it.be/tripled/poker:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: SENTRY_DSN
              value: https://8ed353ea4add4d6ea2d04c153c211746@sentry.rotate-it.be/3?stacktrace.app.packages=io.tripled
            - name: OPENTRACING_JAEGER_HTTP-SENDER_URL
              value: https://tracethis.rotate-it.be/api/traces
            - name: ELASTIC_APM_SERVICE_NAME
              value: poker-service
            - name: ELASTIC_APM_SECRET_TOKEN
              value: fn6xvjk4w7zt845rr5q7vcx4
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: io.tripled
            - name: ELASTIC_APM_SERVER_URLS
              value: https://apm-server-quickstart-apm-http.default:8200
            - name: ELASTIC_APM_VERIFY_SERVER_CERT
              value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: poker-svc
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: production
