#
# infra - graphql
#
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: true
    version: 0.12.0
  props:
    resources:
#      query: query.graphql
#      defaultQuery: defaultQuery.graphql
#      variables: variables.graphql
    variables:
      editorTheme: "solarized light"
#  headers:
#    Authorization: "Bearer <your-token>"


#
# technical & business metrics
#
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 8081 # splits management from the publicly reachable part of the application
  endpoints:
    web:
      exposure:
        include: "*"
