rickroll:
  paths: "/admin"
  file-extensions: "php"

#
# infra - graphql
#
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    actuator-metrics: true
    tracingEnabled: false
    websocket:
      enabled: true
    subscriptions:
      websocket:
        path: /subscriptions

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  static:
    basePath: /
  enabled: true
  pageTitle: Open Triple D Poker - Graphiql
  cdn:
    enabled: true
    version: 0.17.5
  props:
    resources:
#      query: query.graphql
#      defaultQuery: defaultQuery.graphql
#      variables: variables.graphql
    variables:
      editorTheme: "darcula"
#  headers:
#    Authorization: "Bearer <your-token>"


#
# technical & business metrics
#
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 8081 # splits management from the publicly reachable part of the application
  endpoints:
    web:
      exposure:
        include: "*"

#
# tracing
#
opentracing:
  jaeger:
    const-sampler:
      decision: true
    http-sender:
      url: https://tracethis.rotate-it.be/api/traces
      #jaeger-collector.jaeger
    enabled: true
    log-spans: false

# spring
spring:
  application:
    name: poker
logging:
  level:
    graphql:
      servlet:
        internal:
          ApolloSubscriptionKeepAliveRunner: ERROR #until better look can be had